# Generated by Django 3.0.7 on 2020-06-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='articles'),
            preserve_default=False,
        ),
    ]
