# Generated by Django 3.0.7 on 2020-06-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.FloatField(default=0),
        ),
    ]
